FROM <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/<ECR_NAMESPACE>/search_engine:latest AS app

FROM nginx:1.25-alpine
COPY --from=app /var/www/public /var/www/public
COPY docker/nginx/ecs.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/ecs-entrypoint.sh /ecs-entrypoint.sh
RUN chmod +x /ecs-entrypoint.sh

EXPOSE 80 443

ENTRYPOINT ["/ecs-entrypoint.sh"]
